### ISSUE TITLE
AdGuard for Android + Proxy Chain with Clash for Android + Fake IP breaks internet access

### ISSUE THREAD

**Issue by SukkaW** [AdguardTeam/AdguardForAndroid#4769]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

4.0.735

### Environment

```markdown
- OS: Android 13
- Device: Google Pixel 7
- Firmware: Google Pixel for Pixel 7, TQ2A.230505.002
```

### Root access

- [X] Yes, I have it.

### Issue Details

Steps to reproduce:

1. Install Clash for Android at https://play.google.com/store/apps/details?id=com.github.kr328.clash
2. Go to Clash for Android, `Profile`, and add the following Clash configuration:

```yaml
port: 7890
socks-port: 7891
# The remote proxy server is not required to repro the issue
# Let's use Clash's direct mode to forward the packets to the Internet directly
mode: direct

dns:
 enable: true
 ipv6: false
 listen: 127.0.0.1:60053
 enhanced-mode: fake-ip
 default-nameserver:
    - 1.0.0.1 # or any DNS server you like
 nameserver:
    - 1.0.0.1 # or any DNS server you like

rules:
  - MATCH,DIRECT
```

I have also uploaded the profile to [pastebin.com](https://pastebin.com/HcxRLZub), so you can also import the above configuration through `Importing from URL`: https://pastebin.com/raw/HcxRLZub

3. Disable Clash's `VpnService`. We will use AdGuard's `VpnService` to redirect the traffic to Clash's SOCKS5 proxy server:

`Clash for Android - Settings - Network`, disable `Route System Traffic`.

4. Click Clash for Android's `Tap to start` to start a local socks5 proxy server at `127.0.0.1:7891`.

5. Go to `AdGuard -> Settings -> Filtering -> Network -> Proxy -> Proxy server` to add Clash proxy server:

- Proxy name: Clash
- Proxy types: SOCKS5
- Proxy host: 127.0.0.1
- Proxy port: 7891
- Route UDP through SOCKS5: enable

`Check connection` and then `Save and select`.

6. Go to `AdGuard - Protection - DNS protection - DNS server - Custom servers` to add Clash as a DNS server:

- Server name: Clash
- Server address: `127.0.0.1:60053`

7. Go to `AdGuard -> Settings -> Filtering - Apps` to prevent Clash for Android's outbound traffic is directed through AdGuard again.

- App management - Clash for Android - Disable `Route traffic through AdGuard`, disable `Filter app content`, disable `Filter HTTPS` and disable `Route app through proxy`.

8. Go to the AdGuard homepage and start protection.
9. Open Chrome browser and visits `adgaurd.com`.

### Expected Behavior

Chrome should open websites.

### Actual Behavior

Chrome shows `ERR_CONNECTION_RESET`.

### Additional Information

Clash uses Fake IP ([RFC3089, A SOCKS-based IPv6/IPv4 Gateway Mechanism](https://www.rfc-editor.org/rfc/rfc3089)) to take over the traffic. Clash's built-in DNS will return a "Fake IPv4" within `198.18.0.1/16`.

When a TCP connection toward the "Fake IP" is received by Clash, Clash will use the Fake IP to get the target domain of the TCP connection.

For some reason, it seems that the Fake IP within `198.18.0.1/16` breaks AdGuard's network stack.
