### ISSUE TITLE
Can not add my own Adguard Home DoT server

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdguardForAndroid#4991]
### Issue Details

For some reasons I can not add my own Adguard Home DoT server to Adguard for Android.

- DoH still works.
- DoT still works when adding it into Android's Private DNS setting.

### Screenshots

Some.screenshots:

![Screenshot_2023-09-23-19-25-02-849-edit_com termux~2](https://github.com/AdguardTeam/AdguardForAndroid/assets/11857205/8d5675a4-443e-466b-bd4c-ad8450bd152c)
![Screenshot_2023-09-23-19-22-54-400-edit_com adguard android~2](https://github.com/AdguardTeam/AdguardForAndroid/assets/11857205/ddbcb0b4-ff77-4590-81db-aacc2502a203)

**Comment by trmdi** [comment]
Solved by setting the TLS option to have `alpnProtocols=dot`.
(My Adguard runs behind Traefik)

**Comment by ketan** [comment]
@trmdi — could you paste your complete traefik & adguard configuration for reference? I'm trying to figure this out, but for the life of me cannot figure out how to set `alpnProtocols`

**Comment by trmdi** [comment]
@ketan 

```yaml
# adguardhome.yml

# DoT
tcp:
  routers:
    dot:
      entryPoints:
        - dot
      rule: HostSNIRegexp(`^([a-z0-9-]\.)?dns\.example\.com$`)
      service: dot
      tls:
        domains:
          - main: "dns.example.com"
            sans:
              - "*.dns.example.com"
        options: dot

  services:
    dot:
      loadBalancer:
        servers:
          - address: "adguardhome:53"

tls:
  options:
    dot:
      alpnProtocols:
        - dot
```
